name: Hard Level CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-push-test:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Скачиваем код репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Логинимся в Docker Hub (чтобы запушить образ)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Собираем и пушим образ в твой репозиторий
    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: docker7904/project-sem-1:latest

    # 4. Настраиваем Go (нужен для запуска тестов)
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    # 5. Делаем скрипты исполняемыми
    - name: Make scripts executable
      run: chmod +x scripts/*.sh

    # 6. Проверяем работу скрипта prepare.sh (требование чек-листа)
    - name: Check prepare.sh (Local Build)
      run: ./scripts/prepare.sh

    # 7. Поднимаем локальное окружение для тестов
    - name: Start Environment (Docker Compose)
      run: |
        sudo docker compose up -d
        sleep 10 # Ждем инициализацию базы

    # 8. Устанавливаем утилиты для тестов
    - name: Install Test Dependencies
      run: sudo apt-get update && sudo apt-get install -y zip unzip postgresql-client

    # 9. Запускаем тесты Сложного уровня
    - name: Run Tests
      run: ./scripts/tests.sh 3 localhost