name: Super Hard CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 1. Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: docker7904/project-sem-1:latest

    # 2. YC CLI
    - name: Install YC CLI
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

    # 3. Auth
    - name: Auth in Yandex Cloud
      env:
        YC_SA_JSON: ${{ secrets.YC_SA_JSON }}
      run: |
        echo "$YC_SA_JSON" > key.json
        yc config profile create sa-profile
        yc config set service-account-key key.json
        yc config set cloud-id $(yc config get cloud-id)

    # 4. Deploy
    - name: Deploy to Yandex
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        CI: true
      run: |
        chmod +x scripts/*.sh
        ./scripts/run.sh

    # 5. Test
    - name: Test Cloud
      run: |
        echo "Testing IP: ${{ env.DEPLOY_IP }}"
        ./scripts/tests.sh 3 ${{ env.DEPLOY_IP }}